language: node_js
node_js:
  - "stable"
# cache:
#   directories:
#     - node_modules
script:
  - yarn install
  - yarn run build
  
deploy:
  provider: surge
  skip_cleanup: true
  domain: spacex-dawood.surge.sh
  project: ./build/
on:
  branch: master